# Generated by Django 3.0.2 on 2021-03-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user_profile',
            new_name='user',
        ),
    ]
