# Generated by Django 3.0.2 on 2021-03-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='user',
            new_name='post',
        ),
    ]
