# Generated by Django 3.0.2 on 2021-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dateTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
