# Generated by Django 3.0.2 on 2021-03-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='captions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
