# Generated by Django 3.0.2 on 2021-07-22 18:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210317_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='captions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
