# Generated by Django 3.0.2 on 2021-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210316_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
