# Generated by Django 3.0.2 on 2021-03-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userform_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Prefer not to disclose')], max_length=200, null=True),
        ),
    ]
