# Generated by Django 3.0.2 on 2021-03-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210316_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
