# Generated by Django 3.2.16 on 2023-01-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210317_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
